import { createContext, useContext, useState, ReactNode } from "react";

type Language = "EN" | "HI";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>("EN");

  const t = (key: string): string => {
    const translation = translations[language]?.[key];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navigation
    "Dashboard": "Dashboard",
    "Documents": "Documents",
    "Calendar": "Calendar",
    "AI Assistant": "AI Assistant",
    "Consultations": "Consultations",
    "Research": "Research",
    "Case Analysis": "Case Analysis",
    "Billing": "Billing",
    "Plans": "Plans",
    "Referrals": "Referrals",
    "Profile": "Profile",
    
    // Navbar
    "Search documents, cases, clients...": "Search documents, cases, clients...",
    "AI": "AI",
    "Alert": "Alert",
    "EMERGENCY": "EMERGENCY",
    "Advocate": "Advocate",
    "Client": "Client",
    "Admin": "Admin",
    "Settings": "Settings",
    "Logout": "Logout",
    
    // Auth Page
    "Yugality AI": "Yugality AI",
    "Your Royal Legal Companion": "Your Royal Legal Companion",
    "LegalEase Pro": "LegalEase Pro",
    "Premium Legal Practice Suite": "Premium Legal Practice Suite",
    "Select Your Role": "Select Your Role",
    "Choose how you want to access the platform": "Choose how you want to access the platform",
    "Advocate Portal": "Advocate Portal",
    "Access your legal practice dashboard": "Access your legal practice dashboard",
    "Client Portal": "Client Portal",
    "Track your legal matters": "Track your legal matters",
    "Admin Console": "Admin Console",
    "System administration & oversight": "System administration & oversight",
    "Welcome Back": "Welcome Back",
    "Sign in to continue to your account": "Sign in to continue to your account",
    "Email": "Email",
    "Password": "Password",
    "Remember me": "Remember me",
    "Sign In": "Sign In",
    "Back to role selection": "Back to role selection",
    "Try Demo": "Try Demo",
    "Case Management": "Case Management",
    "Document Drafting": "Document Drafting",
    "Court Calendar": "Court Calendar",
    
    // AI Assistant
    "Mode:": "Mode:",
    "Automatic": "Automatic",
    "Manual": "Manual",
    "Ask": "Ask",
    "Draft": "Draft",
    "Quick Actions": "Quick Actions",
    "Prompt Library": "Prompt Library",
    "Summarize document": "Summarize document",
    "Case law research": "Case law research",
    "Draft legal notice": "Draft legal notice",
    "Strategic advice": "Strategic advice",
    "Ask anything...": "Ask anything...",
    "Powered by": "Powered by",
    "Private & Secure": "Private & Secure",
    "DOCUMENT ANALYSIS": "DOCUMENT ANALYSIS",
    "Summarize this contract": "Summarize this contract",
    "Find key clauses": "Find key clauses",
    "Check for risks": "Check for risks",
    "CASE RESEARCH": "CASE RESEARCH",
    "Find similar cases": "Find similar cases",
    "Precedent analysis": "Precedent analysis",
    "Court rulings": "Court rulings",
    "DRAFTING": "DRAFTING",
    "Draft affidavit": "Draft affidavit",
    "Reply to notice": "Reply to notice",
    "Legal opinion": "Legal opinion",
    
    // Dashboard
    "Welcome back": "Welcome back",
    "Here's what's happening with your cases today": "Here's what's happening with your cases today",
    "Active Cases": "Active Cases",
    "Pending Tasks": "Pending Tasks",
    "Upcoming Hearings": "Upcoming Hearings",
    "View all": "View all",
    "Recent Documents": "Recent Documents",
    "Drop files here or click to upload": "Drop files here or click to upload",
    "Today's Tasks": "Today's Tasks",
    "completed": "completed",
    "Recent Activity": "Recent Activity",
    "Key Clients": "Key Clients",
    "Billing Overview": "Billing Overview",
    "This month": "This month",
    "Total Revenue": "Total Revenue",
    "Collected": "Collected",
    "Recent Invoices": "Recent Invoices",
    "AI Insights": "AI Insights",
    "Powered by Yugality AI": "Powered by Yugality AI",
    "Open AI Assistant": "Open AI Assistant",
    "Critical Deadlines": "Critical Deadlines",
    "urgent": "urgent",
    "upcoming": "upcoming",
    "Tomorrow": "Tomorrow",
    "days left": "days left",
    "Hearing": "Hearing",
    "Arguments": "Arguments",
    "Mediation": "Mediation",
    "Today": "Today",
    "filed": "filed",
    "pending": "pending",
    "Pending": "Pending",
    "Active": "Active",
    "Resolved": "Resolved",
    "Review Now": "Review Now",
    "Learn More": "Learn More",
    "Success Rate": "Success Rate",
    "High Risk": "High Risk",
    "Pending Verdict": "Pending Verdict",
    "Live Analytics": "Live Analytics",
    "Track progress and insights for all your cases": "Track progress and insights for all your cases",
    "Case Trends": "Case Trends",
    "Last 6 months performance": "Last 6 months performance",
    "Won": "Won",
    "Ongoing": "Ongoing",
    "Win Rate": "Win Rate",
    "Last 12 months": "Last 12 months",
    "Cases Won": "Cases Won",
    "This year": "This year",
    "Case Distribution": "Case Distribution",
    "By practice area": "By practice area",
    "Risk Analysis": "Risk Analysis",
    "Current risk levels": "Current risk levels",
    
    // Common
    "View All": "View All",
    "Loading...": "Loading...",
    "Save": "Save",
    "Cancel": "Cancel",
    "Edit": "Edit",
    "Delete": "Delete",
    "Add": "Add",
    "Upload": "Upload",
    "Download": "Download",
    "Close": "Close",
    
    // Calendar Page
    "Consultation Booking": "Consultation Booking",
    "Manage client consultations and availability": "Manage client consultations and availability",
    "Calendar View": "Calendar View",
    "Add Availability": "Add Availability",
    "Current Bookings": "Current Bookings",
    "Manage Availability": "Manage Availability",
    "New Booking": "New Booking",
    "Case Sync": "Case Sync",
    "Today's Consultations": "Today's Consultations",
    "This Week": "This Week",
    "Revenue (Week)": "Revenue (Week)",
    "New Clients": "New Clients",
    "Upcoming Consultations": "Upcoming Consultations",
    "Join Call": "Join Call",
    "View Details": "View Details",
    "Confirmed": "Confirmed",
    "Pending Payment": "Pending Payment",
    
    // Research Page
    "Legal Research": "Legal Research",
    "Search through extensive legal databases and case law": "Search through extensive legal databases and case law",
    "Advanced Legal Search": "Advanced Legal Search",
    "Search cases, statutes, regulations, or legal concepts...": "Search cases, statutes, regulations, or legal concepts...",
    "All Categories": "All Categories",
    "Case Law": "Case Law",
    "Statutes": "Statutes",
    "Regulations": "Regulations",
    "Jurisdiction": "Jurisdiction",
    "Year Range": "Year Range",
    "All Jurisdictions": "All Jurisdictions",
    "All Years": "All Years",
    "More Filters": "More Filters",
    "Recent Searches:": "Recent Searches:",
    "Search Results": "Search Results",
    "Databases": "Databases",
    "Saved Research": "Saved Research",
    "AI Research Assistant": "AI Research Assistant",
    "Found {count} results in {time} seconds": "Found {count} results in {time} seconds",
    "Sort by Relevance": "Sort by Relevance",
    "Sort by Date": "Sort by Date",
    "Sort by Citations": "Sort by Citations",
    "High Relevance": "High Relevance",
    
    // Referrals Page
    "Referral Board": "Referral Board",
    "Connect with lawyers and manage referrals": "Connect with lawyers and manage referrals",
    "Post Referral": "Post Referral",
    "Network Lawyers": "Network Lawyers",
    "Available for referrals": "Available for referrals",
    "Active Requests": "Active Requests",
    "Awaiting assignment": "Awaiting assignment",
    "My Referrals": "My Referrals",
    "Total sent": "Total sent",
    "Earnings": "Earnings",
    "From referral commissions": "From referral commissions",
    "Lawyer Directory": "Lawyer Directory",
    "Referral Requests": "Referral Requests",
    "Search lawyers by name or specialty...": "Search lawyers by name or specialty...",
    "All Specialties": "All Specialties",
    "All Locations": "All Locations",
    "Available": "Available",
    "Busy": "Busy",
    "Refer Case": "Refer Case",
    "years experience": "years experience",
    "cases": "cases",
  },
  HI: {
    // Navigation
    "Dashboard": "डैशबोर्ड",
    "Documents": "दस्तावेज़",
    "Calendar": "कैलेंडर",
    "AI Assistant": "AI सहायक",
    "Consultations": "परामर्श",
    "Research": "अनुसंधान",
    "Case Analysis": "मामले का विश्लेषण",
    "Billing": "बिलिंग",
    "Plans": "योजनाएं",
    "Referrals": "रेफरल",
    "Profile": "प्रोफ़ाइल",
    
    // Navbar
    "Search documents, cases, clients...": "दस्तावेज़, मामले, ग्राहक खोजें...",
    "AI": "AI",
    "Alert": "अलर्ट",
    "EMERGENCY": "आपातकाल",
    "Advocate": "अधिवक्ता",
    "Client": "ग्राहक",
    "Admin": "प्रशासक",
    "Settings": "सेटिंग्स",
    "Logout": "लॉग आउट",
    
    // Auth Page
    "Yugality AI": "युगैलिटी AI",
    "Your Royal Legal Companion": "आपका शाही कानूनी साथी",
    "LegalEase Pro": "लीगलईज़ प्रो",
    "Premium Legal Practice Suite": "प्रीमियम कानूनी अभ्यास सूट",
    "Select Your Role": "अपनी भूमिका चुनें",
    "Choose how you want to access the platform": "चुनें कि आप प्लेटफ़ॉर्म तक कैसे पहुंचना चाहते हैं",
    "Advocate Portal": "अधिवक्ता पोर्टल",
    "Access your legal practice dashboard": "अपने कानूनी अभ्यास डैशबोर्ड तक पहुंचें",
    "Client Portal": "ग्राहक पोर्टल",
    "Track your legal matters": "अपने कानूनी मामलों को ट्रैक करें",
    "Admin Console": "प्रशासक कंसोल",
    "System administration & oversight": "सिस्टम प्रशासन और निरीक्षण",
    "Welcome Back": "वापसी पर स्वागत है",
    "Sign in to continue to your account": "अपने खाते में जारी रखने के लिए साइन इन करें",
    "Email": "ईमेल",
    "Password": "पासवर्ड",
    "Remember me": "मुझे याद रखें",
    "Sign In": "साइन इन करें",
    "Back to role selection": "भूमिका चयन पर वापस जाएं",
    "Try Demo": "डेमो आज़माएं",
    "Case Management": "मामला प्रबंधन",
    "Document Drafting": "दस्तावेज़ ड्राफ्टिंग",
    "Court Calendar": "कोर्ट कैलेंडर",
    
    // AI Assistant
    "Mode:": "मोड:",
    "Automatic": "स्वचालित",
    "Manual": "मैनुअल",
    "Ask": "पूछें",
    "Draft": "ड्राफ्ट",
    "Quick Actions": "त्वरित कार्रवाई",
    "Prompt Library": "प्रॉम्प्ट लाइब्रेरी",
    "Summarize document": "दस्तावेज़ सारांश",
    "Case law research": "केस कानून अनुसंधान",
    "Draft legal notice": "कानूनी नोटिस ड्राफ्ट",
    "Strategic advice": "रणनीतिक सलाह",
    "Ask anything...": "कुछ भी पूछें...",
    "Powered by": "द्वारा संचालित",
    "Private & Secure": "निजी और सुरक्षित",
    "DOCUMENT ANALYSIS": "दस्तावेज़ विश्लेषण",
    "Summarize this contract": "इस अनुबंध का सारांश दें",
    "Find key clauses": "मुख्य खंड खोजें",
    "Check for risks": "जोखिमों की जांच करें",
    "CASE RESEARCH": "मामला अनुसंधान",
    "Find similar cases": "समान मामले खोजें",
    "Precedent analysis": "पूर्व उदाहरण विश्लेषण",
    "Court rulings": "अदालत के फैसले",
    "DRAFTING": "ड्राफ्टिंग",
    "Draft affidavit": "शपथ पत्र का ड्राफ्ट",
    "Reply to notice": "नोटिस का जवाब",
    "Legal opinion": "कानूनी राय",
    
    // Dashboard
    "Welcome back": "वापसी पर स्वागत है",
    "Here's what's happening with your cases today": "आज आपके मामलों में क्या हो रहा है",
    "Active Cases": "सक्रिय मामले",
    "Pending Tasks": "लंबित कार्य",
    "Upcoming Hearings": "आगामी सुनवाई",
    "View all": "सभी देखें",
    "Recent Documents": "हाल के दस्तावेज़",
    "Drop files here or click to upload": "फ़ाइलें यहाँ छोड़ें या अपलोड करने के लिए क्लिक करें",
    "Today's Tasks": "आज के कार्य",
    "completed": "पूर्ण",
    "Recent Activity": "हाल की गतिविधि",
    "Key Clients": "मुख्य ग्राहक",
    "Billing Overview": "बिलिंग अवलोकन",
    "This month": "इस महीने",
    "Total Revenue": "कुल राजस्व",
    "Collected": "एकत्रित",
    "Recent Invoices": "हाल के चालान",
    "AI Insights": "AI अंतर्दृष्टि",
    "Powered by Yugality AI": "युगैलिटी AI द्वारा संचालित",
    "Open AI Assistant": "AI सहायक खोलें",
    "Critical Deadlines": "महत्वपूर्ण समय सीमा",
    "urgent": "अत्यावश्यक",
    "upcoming": "आगामी",
    "Tomorrow": "कल",
    "days left": "दिन शेष",
    "Hearing": "सुनवाई",
    "Arguments": "तर्क",
    "Mediation": "मध्यस्थता",
    "Today": "आज",
    "filed": "दर्ज",
    "pending": "लंबित",
    "Pending": "लंबित",
    "Active": "सक्रिय",
    "Resolved": "हल हो गया",
    "Review Now": "अभी समीक्षा करें",
    "Learn More": "और जानें",
    "Success Rate": "सफलता दर",
    "High Risk": "उच्च जोखिम",
    "Pending Verdict": "लंबित फैसला",
    "Live Analytics": "लाइव विश्लेषण",
    "Track progress and insights for all your cases": "अपने सभी मामलों की प्रगति और अंतर्दृष्टि ट्रैक करें",
    "Case Trends": "मामले के रुझान",
    "Last 6 months performance": "पिछले 6 महीनों का प्रदर्शन",
    "Won": "जीता",
    "Ongoing": "चल रहा है",
    "Win Rate": "जीत दर",
    "Last 12 months": "पिछले 12 महीने",
    "Cases Won": "मामले जीते",
    "This year": "इस वर्ष",
    "Case Distribution": "मामला वितरण",
    "By practice area": "अभ्यास क्षेत्र द्वारा",
    "Risk Analysis": "जोखिम विश्लेषण",
    "Current risk levels": "वर्तमान जोखिम स्तर",
    
    // Common
    "View All": "सभी देखें",
    "Loading...": "लोड हो रहा है...",
    "Save": "सहेजें",
    "Cancel": "रद्द करें",
    "Edit": "संपादित करें",
    "Delete": "हटाएं",
    "Add": "जोड़ें",
    "Upload": "अपलोड करें",
    "Download": "डाउनलोड करें",
    "Close": "बंद करें",
    
    // Calendar Page
    "Consultation Booking": "परामर्श बुकिंग",
    "Manage client consultations and availability": "ग्राहक परामर्श और उपलब्धता प्रबंधित करें",
    "Calendar View": "कैलेंडर दृश्य",
    "Add Availability": "उपलब्धता जोड़ें",
    "Current Bookings": "वर्तमान बुकिंग",
    "Manage Availability": "उपलब्धता प्रबंधित करें",
    "New Booking": "नई बुकिंग",
    "Case Sync": "केस सिंक",
    "Today's Consultations": "आज के परामर्श",
    "This Week": "इस सप्ताह",
    "Revenue (Week)": "राजस्व (सप्ताह)",
    "New Clients": "नए ग्राहक",
    "Upcoming Consultations": "आगामी परामर्श",
    "Join Call": "कॉल में शामिल हों",
    "View Details": "विवरण देखें",
    "Confirmed": "पुष्टि की गई",
    "Pending Payment": "भुगतान लंबित",
    
    // Research Page
    "Legal Research": "कानूनी अनुसंधान",
    "Search through extensive legal databases and case law": "व्यापक कानूनी डेटाबेस और केस कानून खोजें",
    "Advanced Legal Search": "उन्नत कानूनी खोज",
    "Search cases, statutes, regulations, or legal concepts...": "मामले, क़ानून, नियम या कानूनी अवधारणाएं खोजें...",
    "All Categories": "सभी श्रेणियां",
    "Case Law": "केस कानून",
    "Statutes": "क़ानून",
    "Regulations": "नियम",
    "Jurisdiction": "अधिकार क्षेत्र",
    "Year Range": "वर्ष सीमा",
    "All Jurisdictions": "सभी अधिकार क्षेत्र",
    "All Years": "सभी वर्ष",
    "More Filters": "अधिक फ़िल्टर",
    "Recent Searches:": "हाल की खोजें:",
    "Search Results": "खोज परिणाम",
    "Databases": "डेटाबेस",
    "Saved Research": "सहेजा गया अनुसंधान",
    "AI Research Assistant": "AI अनुसंधान सहायक",
    "Found {count} results in {time} seconds": "{time} सेकंड में {count} परिणाम मिले",
    "Sort by Relevance": "प्रासंगिकता के अनुसार क्रमबद्ध करें",
    "Sort by Date": "तिथि के अनुसार क्रमबद्ध करें",
    "Sort by Citations": "उद्धरण के अनुसार क्रमबद्ध करें",
    "High Relevance": "उच्च प्रासंगिकता",
    
    // Referrals Page
    "Referral Board": "रेफरल बोर्ड",
    "Connect with lawyers and manage referrals": "वकीलों से जुड़ें और रेफरल प्रबंधित करें",
    "Post Referral": "रेफरल पोस्ट करें",
    "Network Lawyers": "नेटवर्क वकील",
    "Available for referrals": "रेफरल के लिए उपलब्ध",
    "Active Requests": "सक्रिय अनुरोध",
    "Awaiting assignment": "असाइनमेंट की प्रतीक्षा में",
    "My Referrals": "मेरे रेफरल",
    "Total sent": "कुल भेजे गए",
    "Earnings": "कमाई",
    "From referral commissions": "रेफरल कमीशन से",
    "Lawyer Directory": "वकील निर्देशिका",
    "Referral Requests": "रेफरल अनुरोध",
    "Search lawyers by name or specialty...": "नाम या विशेषता से वकील खोजें...",
    "All Specialties": "सभी विशेषताएं",
    "All Locations": "सभी स्थान",
    "Available": "उपलब्ध",
    "Busy": "व्यस्त",
    "Refer Case": "केस रेफर करें",
    "years experience": "वर्ष का अनुभव",
    "cases": "मामले",
    
    // Admin Dashboard
    "Admin Dashboard": "प्रशासक डैशबोर्ड",
    "Total Users": "कुल उपयोगकर्ता",
    "Active Lawyers": "सक्रिय वकील",
    "Total Revenue": "कुल राजस्व",
    "System Health": "सिस्टम स्वास्थ्य",
    "All systems operational": "सभी सिस्टम चालू",
    "User Growth Trends": "उपयोगकर्ता वृद्धि रुझान",
    "Subscription Distribution": "सदस्यता वितरण",
    "Recent Users": "हाल के उपयोगकर्ता",
    "Recent Activities": "हाल की गतिविधियां",
    "System Alerts": "सिस्टम अलर्ट",
    "System Status": "सिस्टम स्थिति",
    
    // Lawyer Dashboard
    "Lawyer Dashboard": "वकील डैशबोर्ड",
    "Pending Hearings": "लंबित सुनवाई",
    "Clients": "ग्राहक",
    "Revenue (MTD)": "राजस्व (मासिक)",
    "My Profile": "मेरी प्रोफ़ाइल",
    "Quick Edit Profile": "त्वरित प्रोफ़ाइल संपादित करें",
    "Name": "नाम",
    "Specialization": "विशेषज्ञता",
    "Bar Council ID": "बार काउंसिल आईडी",
    "Experience": "अनुभव",
    "years": "वर्ष",
    "Update Profile": "प्रोफ़ाइल अपडेट करें",
    
    // Client Dashboard
    "Client Dashboard": "ग्राहक डैशबोर्ड",
    "Messages": "संदेश",
    "Your Advocate": "आपका अधिवक्ता",
    "Contact Advocate": "अधिवक्ता से संपर्क करें",
    "Schedule Meeting": "बैठक निर्धारित करें",
    "Subscription Plans": "सदस्यता योजनाएं",
    "Choose Your Plan": "अपनी योजना चुनें",
    "Basic Plan": "मूल योजना",
    "Professional Plan": "व्यावसायिक योजना",
    "Enterprise Plan": "एंटरप्राइज़ योजना",
    "Get Started": "शुरू करें",
    "Upgrade Now": "अभी अपग्रेड करें",
    "Current Plan": "वर्तमान योजना",
    
    // Common Dashboard Elements
    "Good morning": "सुप्रभात",
    "Good afternoon": "शुभ दोपहर",
    "Good evening": "शुभ संध्या",
    "today": "आज",
    "Next Hearing": "अगली सुनवाई",
    "Progress": "प्रगति",
    "Status": "स्थिति",
    "In Progress": "प्रगति में",
    "Completed": "पूर्ण",
    "Under Review": "समीक्षाधीन",
    "Pending": "लंबित",
    "Urgent": "अत्यावश्यक",
    "Priority": "प्राथमिकता",
  }
};
